name: Build & Deploy to Local Kubernetes new, mujhe bahut maja aaya

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build -t nginx-demo:latest .

      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml

      - name: Force deployment update
        run: |
          kubectl rollout restart deployment nginx-demo
