name: Echo Print

on:
  push:

jobs:
  print-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print message
        run: echo "Hello from GitHub CI/CD!"

  test-job:
     runs-on: ubuntu-latest
     steps:
       - name: test my print
         run: echo "my test first on github"

        
